#!/bin/bash
###############################################################################
# Movie List Creator Script by Luis Alvarado
# Creates File with Movie Name, Resolution, File Type & Quality
# CONFIG Variables

# FOLDER Variable is where all your movies are. Must not end with a backslash.
# NOTE: The name of the movies is extracted from the movie's folder, if the
#       folder is called "..Movies/The Rabbit" then the name of the movie in
#       that folder would be "The Rabbit".

folder="/media/cyrex/xtreme/Movies"

# FINAL Variable is the name of the file you wish to create with the Movie List.

final="moviefinal.txt"

# NOTE: Movie Name can not have a comma "," in the name since this is the
#       separator used to check the quality of the movie.

###############################################################################

here=$(pwd)
percent=$(ls "$folder/"|wc -l| while read pipe; do echo "scale=3; 100/$pipe"; done|bc)
total=$(ls "$folder/"|wc -l)
movies=0
quality=1

clear

echo "Processing Movies..."
echo ""

rm tempmovies 2> /dev/null

for dir in "$folder"/*
do
  (cd "$dir" && found=$(pwd) && echo ${found##/*/}|tr -s '\n' ', ' >> $here/tempmovies &&
  	exiftool -ext .mkv -ext .m4v -ext .mp4 -ext .avi -ext .mpg * -p '$ImageSize, $FileType' >> $here/tempmovies)
	let movies=movies+1
	base=$(echo "scale=3; $percent * $movies" | bc)
	if (($movies == $total))
	then
		echo -ne " Total: 100% Done / $movies Movies Added!"\\r
	else
		echo -ne " Total: $base% Done / $movies Movies Added!"\\r
	fi
done

echo " "
echo " Detecting Movie Quality..."
echo " "

rm $final 2> /dev/null

cat tempmovies | while read MovieName;

do
	echo -ne " Summary: $quality Quality Checks Done!"\\r
	echo "$MovieName" | cut -d ',' -f2 | cut -d 'x' -f2 | sort | uniq | while read MovieRes;
	do
		if (($MovieRes>=304 && $MovieRes<=370))
        then
        	echo "$MovieName, DVD LOW-RES"
		elif (($MovieRes>=241 && $MovieRes<=369))
		then
			echo "$MovieName, DVD HI-RES"
		elif (($MovieRes>=371 && $MovieRes<=480))
		then
			echo "$MovieName, 480p SD"
		elif (($MovieRes>=481 && $MovieRes<=760))
		then
			echo "$MovieName, 720p HD"
		elif (($MovieRes>=761 && $MovieRes<=1200))
		then
			echo "$MovieName, 1080p HD"
		else
			echo "$MovieName, VCD"
		fi >> $final
	done
	let quality=quality+1
done

hd=$(cat moviefinal.txt |grep -e "1080p HD" -e "720p HD"|wc -l)
sd=$(cat moviefinal.txt |grep -ve "1080p HD" -ve "720p HD"|wc -l)

echo " "
echo "----------------"
cat $final | cut -d ',' -f4| sort | uniq -c
echo "----------------"
echo " "
echo "$hd HD Total Movies"
echo "$sd SD Total Movies"
echo " "

rm tempmovies 2> /dev/null

echo "File $final Created!"
